name: KeepItems
main: net.robinjam.bukkit.keepitems.KeepItems
version: ${project.version}
author: robinjam

permissions:
  keep-items.*:
    description: Allows the player to keep both their experience and their items upon death
    default: op
    children:
      keep-items.items: true
      keep-items.experience: true
  
  keep-items.items:
    description: Allows the player to keep their items upon death
    default: false
  
  keep-items.experience:
    description: Allows the player to keep their experience upon death
    default: false
